-- Lightweight family context for an existing Person. No legacy table or route changes.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE IF NOT EXISTS public.households (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anchor_person_id bigint NOT NULL REFERENCES public.persons(id) ON DELETE RESTRICT,
  important_facts text CHECK (important_facts IS NULL OR length(important_facts) <= 2000),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.household_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id bigint NOT NULL REFERENCES public.households(id) ON DELETE RESTRICT,
  person_id bigint NOT NULL REFERENCES public.persons(id) ON DELETE RESTRICT,
  relationship_to_anchor text NOT NULL CHECK (relationship_to_anchor IN
    ('spouse', 'child', 'parent', 'sibling', 'other')),
  confirmed_at timestamptz NOT NULL,
  confirmed_by_uid text NOT NULL CHECK (btrim(confirmed_by_uid) <> ''),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

DO $shape$ BEGIN
  IF (SELECT count(*) FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'households') <> 6
     OR (SELECT count(*) FROM pg_constraint
         WHERE conrelid = 'public.households'::regclass AND contype = 'f') <> 1
     OR (SELECT count(*) FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = 'household_members') <> 9
     OR (SELECT count(*) FROM pg_constraint
         WHERE conrelid = 'public.household_members'::regclass AND contype = 'f') <> 2 THEN
    RAISE EXCEPTION 'household tables exist with incompatible shape';
  END IF;
END $shape$;

-- One active family context per anchor; a person cannot be listed twice in it.
CREATE UNIQUE INDEX IF NOT EXISTS households_active_anchor_key
  ON public.households(anchor_person_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS household_members_active_person_key
  ON public.household_members(household_id, person_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS household_members_person_idx
  ON public.household_members(person_id) WHERE deleted_at IS NULL;

ALTER TABLE public.households ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.household_members ENABLE ROW LEVEL SECURITY;
DO $policy$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public'
                 AND tablename = 'households' AND policyname = 'households_service_only') THEN
    CREATE POLICY households_service_only ON public.households FOR ALL TO service_role
      USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public'
                 AND tablename = 'household_members' AND policyname = 'household_members_service_only') THEN
    CREATE POLICY household_members_service_only ON public.household_members FOR ALL TO service_role
      USING (true) WITH CHECK (true);
  END IF;
END $policy$;
REVOKE ALL ON TABLE public.households, public.household_members FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.households, public.household_members TO service_role;
REVOKE ALL ON SEQUENCE public.households_id_seq, public.household_members_id_seq
  FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.households_id_seq, public.household_members_id_seq
  TO service_role;

COMMENT ON TABLE public.households IS
  'One optional lightweight family context per anchor Person; facts are human-entered text, not wealth data';
COMMENT ON TABLE public.household_members IS
  'Existing Person linked relative to household anchor; confirmed_at and confirmed_by_uid are required';
COMMIT;
