-- Directed Person-to-Person relationship layer, independent of legacy stages.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE IF NOT EXISTS public.relationships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_person_id bigint NOT NULL REFERENCES public.persons(id) ON DELETE RESTRICT,
  to_person_id bigint NOT NULL REFERENCES public.persons(id) ON DELETE RESTRICT,
  relationship_type text NOT NULL CHECK (btrim(relationship_type) <> ''),
  relationship_stage text CHECK (relationship_stage IS NULL OR btrim(relationship_stage) <> ''),
  strength text CHECK (strength IS NULL OR btrim(strength) <> ''),
  trust_level text CHECK (trust_level IS NULL OR btrim(trust_level) <> ''),
  trend text CHECK (trend IS NULL OR btrim(trend) <> ''),
  introduced_by_person_id bigint REFERENCES public.persons(id) ON DELETE RESTRICT,
  context jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(context) = 'object'),
  last_meaningful_interaction_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT relationships_distinct_people CHECK (from_person_id <> to_person_id)
);

DO $shape$ BEGIN
  IF (SELECT count(*) FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'relationships') <> 14
     OR NOT EXISTS (SELECT 1 FROM pg_constraint
       WHERE conrelid = 'public.relationships'::regclass AND conname = 'relationships_distinct_people')
     OR (SELECT count(*) FROM pg_constraint
         WHERE conrelid = 'public.relationships'::regclass AND contype = 'f') <> 3 THEN
    RAISE EXCEPTION 'relationships exists with incompatible shape';
  END IF;
END $shape$;

-- The reverse edge is a distinct relationship. Soft-deleted edges may be recreated.
CREATE UNIQUE INDEX IF NOT EXISTS relationships_directed_active_key
  ON public.relationships(from_person_id, to_person_id, relationship_type)
  WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS relationships_from_active_idx
  ON public.relationships(from_person_id, updated_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS relationships_to_active_idx
  ON public.relationships(to_person_id, updated_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS relationships_introducer_idx
  ON public.relationships(introduced_by_person_id)
  WHERE introduced_by_person_id IS NOT NULL AND deleted_at IS NULL;

ALTER TABLE public.relationships ENABLE ROW LEVEL SECURITY;
DO $policy$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies
                 WHERE schemaname = 'public' AND tablename = 'relationships'
                   AND policyname = 'relationships_service_only') THEN
    CREATE POLICY relationships_service_only ON public.relationships FOR ALL TO service_role
      USING (true) WITH CHECK (true);
  END IF;
END $policy$;
REVOKE ALL ON TABLE public.relationships FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.relationships TO service_role;
REVOKE ALL ON SEQUENCE public.relationships_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.relationships_id_seq TO service_role;

COMMENT ON TABLE public.relationships IS
  'Directed relationship from one Person to another; higher-level model, no legacy stage synchronization';
COMMENT ON COLUMN public.relationships.relationship_stage IS
  'Independent higher-level stage, not customers.customer_stage, recruit_candidates.stage or activity_speakers.relationship_stage';
COMMENT ON COLUMN public.relationships.context IS 'Structured relationship context; must be a JSON object';
COMMIT;
