-- Shared knowledge catalog. No existing CRM objects or flows are changed.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

DO $guard$ BEGIN
  IF to_regclass('public.knowledge_items') IS NOT NULL
     OR to_regclass('public.knowledge_items_id_seq') IS NOT NULL THEN
    RAISE EXCEPTION 'public.knowledge_items objects already exist; inspect before migrating';
  END IF;
END $guard$;

CREATE TABLE public.knowledge_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_type text NOT NULL
    CHECK (item_type IN ('product', 'policy', 'company', 'evidence',
      'case', 'story', 'regulation', 'personal_experience')),
  source text NOT NULL CHECK (length(btrim(source)) BETWEEN 1 AND 1024),
  source_date date,
  valid_from date,
  valid_to date,
  verified boolean NOT NULL DEFAULT false,
  confidence numeric(4,3) CHECK (confidence BETWEEN 0 AND 1),
  content text NOT NULL CHECK (length(btrim(content)) > 0),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
    CHECK (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_items_valid_period_check CHECK (
    valid_from IS NULL OR valid_to IS NULL OR valid_from <= valid_to
  )
);

CREATE INDEX knowledge_items_type_verified_valid_to_idx
  ON public.knowledge_items(item_type, verified, valid_to);
CREATE INDEX knowledge_items_source_date_idx
  ON public.knowledge_items(source_date DESC, id DESC);

ALTER TABLE public.knowledge_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_items FORCE ROW LEVEL SECURITY;
CREATE POLICY knowledge_items_service_read ON public.knowledge_items
  FOR SELECT TO service_role USING (true);
CREATE POLICY knowledge_items_service_insert ON public.knowledge_items
  FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY knowledge_items_service_update ON public.knowledge_items
  FOR UPDATE TO service_role USING (true) WITH CHECK (true);

REVOKE ALL ON TABLE public.knowledge_items FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.knowledge_items TO service_role;
REVOKE ALL ON SEQUENCE public.knowledge_items_id_seq FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.knowledge_items_id_seq TO service_role;

COMMENT ON TABLE public.knowledge_items IS
  'Provenance-aware shared knowledge; verification defaults false and is not inferred by AI';
COMMENT ON COLUMN public.knowledge_items.item_type IS
  'product, policy, company, evidence, case, story, regulation or personal_experience';
COMMENT ON COLUMN public.knowledge_items.source IS
  'Human-readable source name, citation or URL; does not imply verification';
COMMENT ON COLUMN public.knowledge_items.source_date IS
  'Date the source was published or recorded, when known';
COMMENT ON COLUMN public.knowledge_items.valid_to IS
  'Inclusive end of the known validity period, when known';
COMMENT ON COLUMN public.knowledge_items.confidence IS
  'Optional assessment from 0.000 to 1.000; independent of verified';
COMMENT ON COLUMN public.knowledge_items.metadata IS
  'Structured source attributes as a JSON object';
COMMIT;
