-- Add a Person-level interaction ledger without changing legacy source tables.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE IF NOT EXISTS public.interactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id bigint NOT NULL REFERENCES public.persons(id) ON DELETE RESTRICT,
  interaction_type text NOT NULL CHECK (length(btrim(interaction_type)) BETWEEN 1 AND 64),
  interaction_at timestamptz NOT NULL,
  channel text CHECK (channel IS NULL OR length(channel) <= 100),
  summary text NOT NULL CHECK (length(btrim(summary)) BETWEEN 1 AND 2000),
  raw_note text CHECK (raw_note IS NULL OR length(raw_note) <= 10000),
  activity_id bigint REFERENCES public.activities(id) ON DELETE RESTRICT,
  source_type text NOT NULL CHECK (source_type IN
    ('manual', 'followups', 'recruit_followups', 'activity_participants')),
  source_id bigint,
  importance smallint NOT NULL DEFAULT 3 CHECK (importance BETWEEN 1 AND 5),
  created_by_uid text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT interactions_source_pair_check CHECK (
    (source_type = 'manual' AND source_id IS NULL AND nullif(btrim(created_by_uid), '') IS NOT NULL)
    OR (source_type <> 'manual' AND source_id IS NOT NULL)
  )
);

DO $shape$ BEGIN
  IF (SELECT count(*) FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'interactions') <> 13
     OR (SELECT count(*) FROM pg_constraint
         WHERE conrelid = 'public.interactions'::regclass AND contype = 'f') <> 2 THEN
    RAISE EXCEPTION 'public.interactions exists with incompatible shape';
  END IF;
END $shape$;

CREATE INDEX IF NOT EXISTS interactions_person_time_idx
  ON public.interactions(person_id, interaction_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS interactions_activity_idx
  ON public.interactions(activity_id) WHERE activity_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS interactions_source_key
  ON public.interactions(source_type, source_id) WHERE source_id IS NOT NULL;

ALTER TABLE public.interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interactions FORCE ROW LEVEL SECURITY;
DO $policy$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public'
                 AND tablename = 'interactions' AND policyname = 'interactions_service_only') THEN
    CREATE POLICY interactions_service_only ON public.interactions FOR ALL TO service_role
      USING (true) WITH CHECK (true);
  END IF;
END $policy$;
REVOKE ALL ON TABLE public.interactions FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.interactions TO service_role;
REVOKE ALL ON SEQUENCE public.interactions_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.interactions_id_seq TO service_role;

COMMENT ON TABLE public.interactions IS
  'Person-level interaction ledger; legacy followups and activity participation remain source records';
COMMENT ON COLUMN public.interactions.source_type IS
  'manual or the public legacy source table; read-through of legacy rows does not insert into this table';
COMMIT;
