-- AI Runtime storage only. No existing table, view, function or route is changed.
BEGIN;
SET LOCAL lock_timeout = '5s';

DO $guard$ BEGIN
  IF to_regclass('public.ai_tasks') IS NOT NULL
     OR to_regclass('public.ai_runs') IS NOT NULL
     OR to_regclass('public.ai_results') IS NOT NULL THEN
    RAISE EXCEPTION 'AI Runtime tables already exist; inspect before migrating';
  END IF;
END $guard$;

CREATE TABLE public.ai_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_type text NOT NULL CHECK (length(btrim(task_type)) > 0),
  skill_name text,
  subject_type text,
  subject_id text,
  status text NOT NULL DEFAULT 'pending' CHECK (length(btrim(status)) > 0),
  capability text,
  input_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  context_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  requires_confirmation boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  CONSTRAINT ai_tasks_subject_pair_check CHECK ((subject_type IS NULL) = (subject_id IS NULL))
);
COMMENT ON TABLE public.ai_tasks IS 'AI Runtime task snapshots; completion is not human approval';
COMMENT ON COLUMN public.ai_tasks.subject_id IS 'Polymorphic public business ID as text; no cross-schema foreign key';
COMMENT ON COLUMN public.ai_tasks.requires_confirmation IS 'Defaults true; future workflow must verify a human decision before business effects';

CREATE TABLE public.ai_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES public.ai_tasks(id) ON DELETE RESTRICT,
  provider text,
  model text,
  input_tokens bigint CHECK (input_tokens >= 0),
  output_tokens bigint CHECK (output_tokens >= 0),
  cached_tokens bigint CHECK (cached_tokens >= 0),
  latency_ms bigint CHECK (latency_ms >= 0),
  success boolean,
  error text,
  cost numeric(18,8) CHECK (cost >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ai_runs_id_task_unique UNIQUE (id, task_id)
);
COMMENT ON TABLE public.ai_runs IS 'Actual execution attempts; provider/model/cost are recorded only when returned';

CREATE TABLE public.ai_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL,
  run_id bigint NOT NULL,
  result_json jsonb NOT NULL,
  rank integer NOT NULL DEFAULT 1 CHECK (rank > 0),
  is_recommended boolean NOT NULL DEFAULT false,
  user_selected boolean NOT NULL DEFAULT false,
  user_edited boolean NOT NULL DEFAULT false,
  final_result_json jsonb,
  feedback text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ai_results_run_task_fk FOREIGN KEY (run_id, task_id)
    REFERENCES public.ai_runs(id, task_id) ON DELETE RESTRICT,
  CONSTRAINT ai_results_final_selected_check CHECK (final_result_json IS NULL OR user_selected),
  CONSTRAINT ai_results_edited_final_check CHECK (NOT user_edited OR final_result_json IS NOT NULL)
);
COMMENT ON TABLE public.ai_results IS 'Generated options and later human selection; flags alone do not authorize a business write';

CREATE INDEX ai_tasks_status_created_idx ON public.ai_tasks(status, created_at DESC);
CREATE INDEX ai_tasks_subject_created_idx ON public.ai_tasks(subject_type, subject_id, created_at DESC)
  WHERE subject_type IS NOT NULL;
CREATE INDEX ai_runs_task_created_idx ON public.ai_runs(task_id, created_at DESC);
CREATE INDEX ai_results_task_rank_idx ON public.ai_results(task_id, rank, id);
CREATE INDEX ai_results_run_task_idx ON public.ai_results(run_id, task_id);
CREATE INDEX ai_results_selected_idx ON public.ai_results(task_id, created_at DESC)
  WHERE user_selected;

ALTER TABLE public.ai_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_results ENABLE ROW LEVEL SECURITY;

-- The foundation has no runtime writer yet. Keep client and anonymous roles out.
-- A future function/RPC access path needs its own scoped permission review.
CREATE POLICY ai_tasks_service_only ON public.ai_tasks FOR ALL TO service_role
  USING (true) WITH CHECK (true);
CREATE POLICY ai_runs_service_only ON public.ai_runs FOR ALL TO service_role
  USING (true) WITH CHECK (true);
CREATE POLICY ai_results_service_only ON public.ai_results FOR ALL TO service_role
  USING (true) WITH CHECK (true);

REVOKE ALL ON TABLE public.ai_tasks, public.ai_runs, public.ai_results FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.ai_tasks, public.ai_runs, public.ai_results TO service_role;
REVOKE ALL ON SEQUENCE public.ai_tasks_id_seq, public.ai_runs_id_seq, public.ai_results_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.ai_tasks_id_seq, public.ai_runs_id_seq, public.ai_results_id_seq TO service_role;
COMMIT;
