-- Person commitments are separate from legacy next_action fields and Today 5.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

DO $guard$ BEGIN
  IF to_regclass('public.commitments') IS NOT NULL
     OR EXISTS (SELECT 1 FROM pg_proc
                WHERE pronamespace = 'public'::regnamespace
                  AND proname = 'commitments_guard') THEN
    RAISE EXCEPTION 'public.commitments objects already exist; inspect before migrating';
  END IF;
END $guard$;

CREATE TABLE public.commitments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id bigint NOT NULL REFERENCES public.persons(id) ON DELETE RESTRICT,
  interaction_id bigint REFERENCES public.interactions(id) ON DELETE RESTRICT,
  commitment_type text NOT NULL
    CHECK (commitment_type IN ('I_PROMISED', 'THEY_PROMISED', 'MUTUAL')),
  content text NOT NULL CHECK (length(btrim(content)) BETWEEN 1 AND 4000),
  due_at timestamptz,
  status text NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'completed', 'cancelled')),
  source text NOT NULL CHECK (source ~ '^[a-z][a-z0-9_]{0,63}$'),
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by_uid text NOT NULL CHECK (length(btrim(created_by_uid)) BETWEEN 1 AND 128),
  completed_by_uid text,
  confirmed_by_uid text,
  confirmed_at timestamptz,
  CONSTRAINT commitments_completion_check CHECK (
    (status = 'completed' AND completed_at IS NOT NULL
      AND nullif(btrim(completed_by_uid), '') IS NOT NULL)
    OR (status <> 'completed' AND completed_at IS NULL AND completed_by_uid IS NULL)
  ),
  CONSTRAINT commitments_ai_confirmation_check CHECK (
    (source !~ '^ai(_|$)' AND confirmed_by_uid IS NULL AND confirmed_at IS NULL)
    OR (source ~ '^ai(_|$)' AND nullif(btrim(confirmed_by_uid), '') IS NOT NULL
        AND confirmed_at IS NOT NULL)
  )
);

CREATE FUNCTION public.commitments_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = public AS $guard$
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF (NEW.person_id, NEW.interaction_id, NEW.source, NEW.created_by_uid,
        NEW.confirmed_by_uid, NEW.confirmed_at)
       IS DISTINCT FROM
       (OLD.person_id, OLD.interaction_id, OLD.source, OLD.created_by_uid,
        OLD.confirmed_by_uid, OLD.confirmed_at) THEN
      RAISE EXCEPTION 'commitment identity and provenance are immutable'
        USING ERRCODE = '23514';
    END IF;
    NEW.updated_at := now();
  END IF;
  IF NEW.interaction_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.interactions AS i
    WHERE i.id = NEW.interaction_id AND i.person_id = NEW.person_id
  ) THEN
    RAISE EXCEPTION 'commitment interaction belongs to another Person'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$guard$;

CREATE TRIGGER commitments_guard_before_write
  BEFORE INSERT OR UPDATE ON public.commitments
  FOR EACH ROW EXECUTE FUNCTION public.commitments_guard();

CREATE INDEX commitments_person_status_due_idx
  ON public.commitments(person_id, status, due_at, id);
CREATE INDEX commitments_open_due_idx
  ON public.commitments(due_at, id)
  WHERE status = 'open' AND due_at IS NOT NULL;
CREATE INDEX commitments_interaction_idx
  ON public.commitments(interaction_id) WHERE interaction_id IS NOT NULL;

ALTER TABLE public.commitments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commitments FORCE ROW LEVEL SECURITY;
CREATE POLICY commitments_service_read ON public.commitments
  FOR SELECT TO service_role USING (true);
CREATE POLICY commitments_service_insert ON public.commitments
  FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY commitments_service_update ON public.commitments
  FOR UPDATE TO service_role USING (true) WITH CHECK (true);
REVOKE ALL ON TABLE public.commitments FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.commitments TO service_role;
REVOKE ALL ON SEQUENCE public.commitments_id_seq FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.commitments_id_seq TO service_role;
REVOKE ALL ON FUNCTION public.commitments_guard() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.commitments_guard() TO service_role;

COMMENT ON TABLE public.commitments IS
  'Person promises: I_PROMISED, THEY_PROMISED or MUTUAL; distinct from legacy next_action';
COMMENT ON COLUMN public.commitments.due_at IS
  'Optional exact deadline; Today displays open commitments due within three Beijing calendar days or overdue';
COMMENT ON COLUMN public.commitments.source IS
  'AI-prefixed sources require a recorded human confirmation before persistence';
COMMIT;
