-- Add a private learning ledger; no existing CRM object or AI flow is changed.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

DO $guard$ BEGIN
  IF to_regclass('public.learnings') IS NOT NULL
     OR to_regclass('public.learnings_id_seq') IS NOT NULL
     OR EXISTS (SELECT 1 FROM pg_proc
                WHERE pronamespace = 'public'::regnamespace
                  AND proname = 'learnings_guard') THEN
    RAISE EXCEPTION 'public.learnings objects already exist; inspect before migrating';
  END IF;
END $guard$;

CREATE TABLE public.learnings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type text NOT NULL CHECK (source_type IN
    ('ai_recommendation', 'user_correction', 'action', 'outcome')),
  source_table text,
  source_id bigint CHECK (source_id > 0),
  situation text NOT NULL CHECK (length(btrim(situation)) BETWEEN 1 AND 2000),
  ai_recommendation text CHECK (ai_recommendation IS NULL OR length(btrim(ai_recommendation)) BETWEEN 1 AND 4000),
  user_decision text CHECK (user_decision IS NULL OR length(btrim(user_decision)) BETWEEN 1 AND 4000),
  actual_action text CHECK (actual_action IS NULL OR length(btrim(actual_action)) BETWEEN 1 AND 4000),
  outcome text CHECK (outcome IS NULL OR length(btrim(outcome)) BETWEEN 1 AND 4000),
  learning text NOT NULL CHECK (length(btrim(learning)) BETWEEN 1 AND 4000),
  confidence numeric(4,3) CHECK (confidence BETWEEN 0 AND 1),
  scope text NOT NULL DEFAULT 'private' CHECK (length(btrim(scope)) BETWEEN 1 AND 128),
  confirmed boolean NOT NULL DEFAULT false,
  confirmed_by_uid text,
  confirmed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT learnings_source_check CHECK (
    (source_type = 'user_correction' AND source_table IS NULL AND source_id IS NULL)
    OR (source_type = 'ai_recommendation'
        AND source_table IS NOT NULL
        AND source_table IN ('ai_recommendations', 'ai_results') AND source_id IS NOT NULL)
    OR (source_type = 'action' AND source_table IS NOT NULL
        AND source_table = 'actions' AND source_id IS NOT NULL)
    OR (source_type = 'outcome' AND source_table IS NOT NULL
        AND source_table = 'outcomes' AND source_id IS NOT NULL)
  ),
  CONSTRAINT learnings_confirmation_check CHECK (
    (NOT confirmed AND confirmed_by_uid IS NULL AND confirmed_at IS NULL)
    OR (confirmed AND confirmed_by_uid IS NOT NULL AND btrim(confirmed_by_uid) <> ''
        AND confirmed_at IS NOT NULL AND user_decision IS NOT NULL
        AND btrim(user_decision) <> '')
  )
);

CREATE FUNCTION public.learnings_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = public AS $guard$
BEGIN
  IF TG_OP = 'INSERT' AND NEW.confirmed THEN
    RAISE EXCEPTION 'learning must be inserted for human review before confirmation'
      USING ERRCODE = '23514';
  END IF;
  IF TG_OP = 'UPDATE' AND
     (NEW.source_type, NEW.source_table, NEW.source_id) IS DISTINCT FROM
     (OLD.source_type, OLD.source_table, OLD.source_id) THEN
    RAISE EXCEPTION 'learning provenance is immutable'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$guard$;
CREATE TRIGGER learnings_guard_before_write
  BEFORE INSERT OR UPDATE ON public.learnings
  FOR EACH ROW EXECUTE FUNCTION public.learnings_guard();

CREATE INDEX learnings_source_idx
  ON public.learnings(source_type, source_table, source_id)
  WHERE source_id IS NOT NULL;
CREATE INDEX learnings_scope_confirmed_idx
  ON public.learnings(scope, confirmed, created_at DESC, id DESC);

ALTER TABLE public.learnings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learnings FORCE ROW LEVEL SECURITY;
CREATE POLICY learnings_service_read ON public.learnings
  FOR SELECT TO service_role USING (true);
CREATE POLICY learnings_service_insert ON public.learnings
  FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY learnings_service_update ON public.learnings
  FOR UPDATE TO service_role USING (true) WITH CHECK (true);
REVOKE ALL ON TABLE public.learnings FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.learnings TO service_role;
REVOKE ALL ON SEQUENCE public.learnings_id_seq FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.learnings_id_seq TO service_role;
REVOKE ALL ON FUNCTION public.learnings_guard() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.learnings_guard() TO service_role;

COMMENT ON TABLE public.learnings IS
  'Reviewable learning candidates from AI recommendations, user corrections, actions or outcomes';
COMMENT ON COLUMN public.learnings.source_table IS
  'Allowlisted public source table; source_id is a soft reference validated by a future writer';
COMMENT ON COLUMN public.learnings.scope IS
  'Private by default; value alone never authorizes retrieval or global reuse';
COMMENT ON COLUMN public.learnings.confirmed IS
  'False on insertion; a later authenticated human review must record decision, UID and time';
COMMIT;
