-- Additive identity layer. Existing customers, views, functions and routes are unchanged.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

-- Keep the one-to-one snapshot stable until this transaction commits.
LOCK TABLE public.customers IN SHARE MODE;
DO $guard$ BEGIN
  IF EXISTS (SELECT 1 FROM public.customers
             WHERE "Id" IS NULL OR customer_name IS NULL OR btrim(customer_name) = '') THEN
    RAISE EXCEPTION 'persons backfill refused: customer ID or name is missing';
  END IF;
END $guard$;

CREATE TABLE IF NOT EXISTS public.persons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name text NOT NULL CHECK (btrim(display_name) <> ''),
  name_key text NOT NULL CHECK (btrim(name_key) <> ''),
  phone text,
  wechat text,
  gender text,
  birthday date,
  occupation text,
  organization text,
  education text,
  source text,
  notes text,
  legacy_customer_id integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamp without time zone,
  CONSTRAINT persons_legacy_customer_id_key UNIQUE (legacy_customer_id)
);

-- IF NOT EXISTS must never hide an incompatible pre-existing table.
DO $shape$ BEGIN
  IF (SELECT count(*) FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'persons') <> 16
     OR EXISTS (
       SELECT 1 FROM (VALUES
         ('id', 'bigint', 'NO'),
         ('display_name', 'text', 'NO'),
         ('name_key', 'text', 'NO'),
         ('phone', 'text', 'YES'),
         ('wechat', 'text', 'YES'),
         ('gender', 'text', 'YES'),
         ('birthday', 'date', 'YES'),
         ('occupation', 'text', 'YES'),
         ('organization', 'text', 'YES'),
         ('education', 'text', 'YES'),
         ('source', 'text', 'YES'),
         ('notes', 'text', 'YES'),
         ('legacy_customer_id', 'integer', 'YES'),
         ('created_at', 'timestamp with time zone', 'NO'),
         ('updated_at', 'timestamp with time zone', 'NO'),
         ('deleted_at', 'timestamp without time zone', 'YES')
       ) expected(column_name, data_type, is_nullable)
       LEFT JOIN information_schema.columns actual
         ON actual.table_schema = 'public' AND actual.table_name = 'persons'
        AND actual.column_name = expected.column_name
       WHERE actual.column_name IS NULL
          OR actual.data_type <> expected.data_type
          OR actual.is_nullable <> expected.is_nullable
     )
     OR NOT EXISTS (
       SELECT 1 FROM pg_constraint
       WHERE conrelid = 'public.persons'::regclass
         AND contype = 'u'
         AND pg_get_constraintdef(oid) = 'UNIQUE (legacy_customer_id)'
     ) THEN
    RAISE EXCEPTION 'persons exists with incompatible columns or missing legacy_customer_id UNIQUE';
  END IF;
END $shape$;

CREATE INDEX IF NOT EXISTS persons_name_key_idx ON public.persons (name_key);
CREATE INDEX IF NOT EXISTS persons_active_name_idx ON public.persons (name_key, id)
  WHERE deleted_at IS NULL;

ALTER TABLE public.persons ENABLE ROW LEVEL SECURITY;
DO $policy$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public'
                 AND tablename = 'persons' AND policyname = 'persons_service_only') THEN
    CREATE POLICY persons_service_only ON public.persons FOR ALL TO service_role
      USING (true) WITH CHECK (true);
  END IF;
END $policy$;
REVOKE ALL ON TABLE public.persons FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.persons TO service_role;
REVOKE ALL ON SEQUENCE public.persons_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.persons_id_seq TO service_role;

-- Preserve original customer values and deletion state. The unique legacy key
-- makes a repeated run a no-op for already imported customers.
INSERT INTO public.persons (
  display_name, name_key, phone, wechat, gender, birthday, occupation,
  organization, education, source, notes, legacy_customer_id,
  created_at, updated_at, deleted_at
)
SELECT
  c.customer_name,
  lower(regexp_replace(btrim(c.customer_name), '[[:space:]]+', ' ', 'g')),
  c.phone, c.wx_account, c.gender, c.birthday, c.occupation,
  NULL, c.education, c.source, c.additional_info, c."Id",
  coalesce(c.created_at, now()), coalesce(c.updated_at, c.created_at, now()), c.deleted_at
FROM public.customers AS c
ON CONFLICT (legacy_customer_id) DO NOTHING;

DO $complete$ BEGIN
  IF EXISTS (
    SELECT 1 FROM public.customers AS c
    LEFT JOIN public.persons AS p ON p.legacy_customer_id = c."Id"
    WHERE p.id IS NULL
  ) THEN
    RAISE EXCEPTION 'persons backfill incomplete';
  END IF;
END $complete$;

COMMENT ON TABLE public.persons IS 'Additive identity layer; customer links are one-to-one at initial backfill only';
COMMENT ON COLUMN public.persons.name_key IS 'Lowercase, whitespace-normalized search key; not unique';
COMMENT ON COLUMN public.persons.legacy_customer_id IS 'Nullable, unique link to existing customers.Id; no customer key or flow changed';
COMMIT;
