-- Add a public outcome ledger without changing existing CRM tables or flows.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

DO $guard$ BEGIN
  IF to_regclass('public.outcomes') IS NOT NULL
     OR to_regclass('public.outcomes_id_seq') IS NOT NULL THEN
    RAISE EXCEPTION 'public.outcomes objects already exist; inspect before migrating';
  END IF;
END $guard$;

CREATE TABLE public.outcomes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_id bigint REFERENCES public.actions(id) ON DELETE SET NULL,
  opportunity_id bigint REFERENCES public.opportunities(id) ON DELETE SET NULL,
  interaction_id bigint REFERENCES public.interactions(id) ON DELETE SET NULL,
  activity_id bigint REFERENCES public.activities(id) ON DELETE SET NULL,
  recruit_candidate_id bigint REFERENCES public.recruit_candidates(id) ON DELETE SET NULL,
  outcome_type text NOT NULL CHECK (length(btrim(outcome_type)) BETWEEN 1 AND 64),
  result text NOT NULL CHECK (length(btrim(result)) BETWEEN 1 AND 4000),
  sentiment text CHECK (sentiment IS NULL OR length(btrim(sentiment)) BETWEEN 1 AND 64),
  relationship_change text CHECK (relationship_change IS NULL OR length(btrim(relationship_change)) BETWEEN 1 AND 2000),
  opportunity_change text CHECK (opportunity_change IS NULL OR length(btrim(opportunity_change)) BETWEEN 1 AND 2000),
  business_value numeric(18,2),
  notes text CHECK (notes IS NULL OR length(notes) <= 8000),
  occurred_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX outcomes_occurred_at_idx ON public.outcomes(occurred_at DESC, id DESC);
CREATE INDEX outcomes_action_idx ON public.outcomes(action_id, occurred_at DESC)
  WHERE action_id IS NOT NULL;
CREATE INDEX outcomes_opportunity_idx ON public.outcomes(opportunity_id, occurred_at DESC)
  WHERE opportunity_id IS NOT NULL;
CREATE INDEX outcomes_interaction_idx ON public.outcomes(interaction_id, occurred_at DESC)
  WHERE interaction_id IS NOT NULL;
CREATE INDEX outcomes_activity_idx ON public.outcomes(activity_id, occurred_at DESC)
  WHERE activity_id IS NOT NULL;
CREATE INDEX outcomes_recruit_candidate_idx ON public.outcomes(recruit_candidate_id, occurred_at DESC)
  WHERE recruit_candidate_id IS NOT NULL;

ALTER TABLE public.outcomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outcomes FORCE ROW LEVEL SECURITY;
CREATE POLICY outcomes_service_read ON public.outcomes
  FOR SELECT TO service_role USING (true);
CREATE POLICY outcomes_service_insert ON public.outcomes
  FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY outcomes_service_update ON public.outcomes
  FOR UPDATE TO service_role USING (true) WITH CHECK (true);
REVOKE ALL ON TABLE public.outcomes FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.outcomes TO service_role;
REVOKE ALL ON SEQUENCE public.outcomes_id_seq FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.outcomes_id_seq TO service_role;

COMMENT ON TABLE public.outcomes IS
  'Observed CRM results; optional links to action, opportunity, interaction, activity and recruit candidate';
COMMENT ON COLUMN public.outcomes.business_value IS
  'Optional signed numeric business value; currency and interpretation are not implied';
COMMENT ON COLUMN public.outcomes.recruit_candidate_id IS
  'Optional link to the existing public.recruit_candidates record';
COMMENT ON COLUMN public.outcomes.action_id IS
  'Links are cleared on hard deletion so legacy source deletion remains possible';
COMMIT;
