-- Add a typed, provenance-preserving Person context ledger. No legacy object changes.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

DO $guard$ BEGIN
  IF to_regclass('public.context_items') IS NOT NULL
     OR EXISTS (SELECT 1 FROM pg_proc
                WHERE pronamespace = 'public'::regnamespace
                  AND proname = 'context_items_validate') THEN
    RAISE EXCEPTION 'context_items objects already exist; inspect before migrating';
  END IF;
END $guard$;

CREATE TABLE public.context_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id bigint NOT NULL REFERENCES public.persons(id) ON DELETE RESTRICT,
  interaction_id bigint REFERENCES public.interactions(id) ON DELETE RESTRICT,
  item_type text NOT NULL CHECK (item_type IN ('fact', 'signal', 'inference')),
  category text NOT NULL DEFAULT 'general'
    CHECK (length(btrim(category)) BETWEEN 1 AND 64),
  content text NOT NULL CHECK (length(btrim(content)) BETWEEN 1 AND 4000),
  structured_value jsonb,
  source_type text NOT NULL
    CHECK (source_type ~ '^[a-z][a-z0-9_]{0,63}$'),
  source_id bigint,
  confidence numeric(4,3) CHECK (confidence BETWEEN 0 AND 1),
  confirmed boolean NOT NULL DEFAULT false,
  confirmed_by_uid text,
  confirmed_at timestamptz,
  valid_from timestamptz,
  valid_to timestamptz,
  last_verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT context_items_source_pair_check CHECK (
    (source_type = 'manual' AND source_id IS NULL)
    OR (source_type <> 'manual' AND source_id IS NOT NULL)
  ),
  CONSTRAINT context_items_interaction_source_check CHECK (
    source_type <> 'interactions'
    OR (interaction_id IS NOT NULL AND source_id = interaction_id)
  ),
  CONSTRAINT context_items_confirmation_check CHECK (
    (NOT confirmed AND confirmed_by_uid IS NULL AND confirmed_at IS NULL)
    OR (confirmed AND confirmed_by_uid IS NOT NULL
        AND btrim(confirmed_by_uid) <> '' AND confirmed_at IS NOT NULL)
  ),
  CONSTRAINT context_items_valid_period_check CHECK (
    valid_from IS NULL OR valid_to IS NULL OR valid_from <= valid_to
  )
);

CREATE FUNCTION public.context_items_validate() RETURNS trigger
LANGUAGE plpgsql SET search_path = public AS $guard$
BEGIN
  IF TG_OP = 'UPDATE' AND
     (NEW.person_id, NEW.interaction_id, NEW.item_type, NEW.source_type, NEW.source_id)
       IS DISTINCT FROM
     (OLD.person_id, OLD.interaction_id, OLD.item_type, OLD.source_type, OLD.source_id) THEN
    RAISE EXCEPTION 'context item identity, type and provenance are immutable'
      USING ERRCODE = '23514';
  END IF;

  IF NEW.interaction_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.interactions AS i
    WHERE i.id = NEW.interaction_id AND i.person_id = NEW.person_id
  ) THEN
    RAISE EXCEPTION 'context item interaction belongs to another Person'
      USING ERRCODE = '23514';
  END IF;

  -- AI Fact Candidates are always inserted unconfirmed. A later human review
  -- path must explicitly record confirmed_by_uid and confirmed_at.
  IF TG_OP = 'INSERT' AND NEW.item_type = 'fact'
     AND NEW.source_type ~ '^ai(_|$)' AND NEW.confirmed THEN
    RAISE EXCEPTION 'AI Fact Candidate cannot be inserted as confirmed'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$guard$;

CREATE TRIGGER context_items_validate_before_write
  BEFORE INSERT OR UPDATE ON public.context_items
  FOR EACH ROW EXECUTE FUNCTION public.context_items_validate();

CREATE INDEX context_items_person_created_idx
  ON public.context_items(person_id, created_at DESC, id DESC);
CREATE INDEX context_items_interaction_idx
  ON public.context_items(interaction_id) WHERE interaction_id IS NOT NULL;
CREATE INDEX context_items_source_idx
  ON public.context_items(source_type, source_id) WHERE source_id IS NOT NULL;
CREATE INDEX context_items_fact_candidates_idx
  ON public.context_items(person_id, created_at DESC)
  WHERE item_type = 'fact' AND NOT confirmed;

ALTER TABLE public.context_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.context_items FORCE ROW LEVEL SECURITY;
CREATE POLICY context_items_service_only ON public.context_items FOR ALL TO service_role
  USING (true) WITH CHECK (true);
REVOKE ALL ON TABLE public.context_items FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.context_items FROM service_role;
GRANT SELECT, INSERT ON TABLE public.context_items TO service_role;
REVOKE ALL ON SEQUENCE public.context_items_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.context_items_id_seq TO service_role;
REVOKE ALL ON FUNCTION public.context_items_validate() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.context_items_validate() TO service_role;

COMMENT ON TABLE public.context_items IS
  'Typed Person context: fact, signal and inference remain distinct; AI Fact Candidates require human review';
COMMENT ON COLUMN public.context_items.source_type IS
  'Canonical public source key; AI-produced items must use ai or an ai_ prefix (for example ai_results)';
COMMENT ON COLUMN public.context_items.confirmed IS
  'Defaults false. AI Fact Candidates cannot be inserted as confirmed; later confirmation requires human UID and time';
COMMENT ON COLUMN public.context_items.interaction_id IS
  'Optional source interaction, validated to belong to the same Person';
COMMIT;
