-- Additive, repeatable role layer. No legacy stage or page changes.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE IF NOT EXISTS public.person_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id bigint NOT NULL REFERENCES public.persons(id) ON DELETE RESTRICT,
  role text NOT NULL CHECK (role IN (
    'customer', 'recruit', 'speaker', 'participant',
    'partner', 'referrer', 'alumni', 'other'
  )),
  origin text NOT NULL DEFAULT 'manual' CHECK (origin IN ('manual', 'legacy_backfill')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT person_roles_person_role_key UNIQUE (person_id, role)
);

DO $shape$ BEGIN
  IF (SELECT count(*) FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'person_roles') <> 6
     OR NOT EXISTS (SELECT 1 FROM pg_constraint
       WHERE conrelid = 'public.person_roles'::regclass AND contype = 'u'
         AND pg_get_constraintdef(oid) = 'UNIQUE (person_id, role)')
     OR NOT EXISTS (SELECT 1 FROM pg_constraint
       WHERE conrelid = 'public.person_roles'::regclass AND contype = 'f'
         AND pg_get_constraintdef(oid) LIKE 'FOREIGN KEY (person_id) REFERENCES persons(id)%') THEN
    RAISE EXCEPTION 'person_roles exists with incompatible shape';
  END IF;
END $shape$;

CREATE INDEX IF NOT EXISTS person_roles_role_person_idx ON public.person_roles(role, person_id);
ALTER TABLE public.person_roles ENABLE ROW LEVEL SECURITY;
DO $policy$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies
                 WHERE schemaname = 'public' AND tablename = 'person_roles'
                   AND policyname = 'person_roles_service_only') THEN
    CREATE POLICY person_roles_service_only ON public.person_roles FOR ALL TO service_role
      USING (true) WITH CHECK (true);
  END IF;
END $policy$;
REVOKE ALL ON TABLE public.person_roles FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.person_roles TO service_role;
REVOKE ALL ON SEQUENCE public.person_roles_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.person_roles_id_seq TO service_role;

-- Only existing explicit IDs are used. No name-based identity guesses.
INSERT INTO public.person_roles (person_id, role, origin)
SELECT p.id, 'customer', 'legacy_backfill' FROM public.persons AS p
WHERE p.legacy_customer_id IS NOT NULL
ON CONFLICT (person_id, role) DO NOTHING;

INSERT INTO public.person_roles (person_id, role, origin)
SELECT DISTINCT p.id, 'recruit', 'legacy_backfill'
FROM public.recruit_candidates AS rc
JOIN public.persons AS p ON p.legacy_customer_id = rc.customer_id
WHERE rc.deleted_at IS NULL
ON CONFLICT (person_id, role) DO NOTHING;

INSERT INTO public.person_roles (person_id, role, origin)
SELECT DISTINCT p.id, 'speaker', 'legacy_backfill'
FROM public.activity_speakers AS s
JOIN public.persons AS p ON p.legacy_customer_id = s.customer_id
WHERE s.deleted_at IS NULL
ON CONFLICT (person_id, role) DO NOTHING;

INSERT INTO public.person_roles (person_id, role, origin)
SELECT DISTINCT p.id, 'participant', 'legacy_backfill'
FROM public.activity_participants AS ap
JOIN public.persons AS p ON p.legacy_customer_id = ap.person_id
WHERE ap.deleted_at IS NULL AND ap.person_type = 'customer'
ON CONFLICT (person_id, role) DO NOTHING;

COMMENT ON TABLE public.person_roles IS
  'Person can hold several roles; initial legacy backfill is a snapshot, not a sync trigger';
COMMENT ON COLUMN public.person_roles.origin IS
  'legacy_backfill marks rows created by this migration for safe rollback; future writes default to manual';
COMMIT;
