-- Add an independent Person action ledger. Existing action-center views stay unchanged.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

DO $guard$ BEGIN
  IF to_regclass('public.actions') IS NOT NULL
     OR EXISTS (SELECT 1 FROM pg_proc
                WHERE pronamespace = 'public'::regnamespace
                  AND proname = 'actions_guard') THEN
    RAISE EXCEPTION 'public.actions objects already exist; inspect before migrating';
  END IF;
END $guard$;

CREATE TABLE public.actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id bigint NOT NULL REFERENCES public.persons(id) ON DELETE RESTRICT,
  opportunity_id bigint REFERENCES public.opportunities(id) ON DELETE RESTRICT,
  interaction_id bigint REFERENCES public.interactions(id) ON DELETE RESTRICT,
  activity_id bigint REFERENCES public.activities(id) ON DELETE RESTRICT,
  action_type text NOT NULL CHECK (length(btrim(action_type)) BETWEEN 1 AND 64),
  title text NOT NULL CHECK (length(btrim(title)) BETWEEN 1 AND 200),
  description text CHECK (description IS NULL OR length(description) <= 4000),
  due_at timestamptz,
  priority text NOT NULL DEFAULT 'medium'
    CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  status text NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'in_progress', 'completed', 'cancelled')),
  source text NOT NULL CHECK (source ~ '^[a-z][a-z0-9_]{0,63}$'),
  urgency_score numeric(5,2) CHECK (urgency_score BETWEEN 0 AND 100),
  impact_score numeric(5,2) CHECK (impact_score BETWEEN 0 AND 100),
  confidence_score numeric(5,2) CHECK (confidence_score BETWEEN 0 AND 100),
  effort_score numeric(5,2) CHECK (effort_score BETWEEN 0 AND 100),
  priority_score numeric(5,2) CHECK (priority_score BETWEEN 0 AND 100),
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by_uid text NOT NULL CHECK (length(btrim(created_by_uid)) BETWEEN 1 AND 128),
  completed_by_uid text,
  confirmed_by_uid text,
  confirmed_at timestamptz,
  CONSTRAINT actions_completion_check CHECK (
    (status = 'completed' AND completed_at IS NOT NULL
      AND nullif(btrim(completed_by_uid), '') IS NOT NULL)
    OR (status <> 'completed' AND completed_at IS NULL AND completed_by_uid IS NULL)
  ),
  CONSTRAINT actions_ai_confirmation_check CHECK (
    (source !~ '^ai(_|$)' AND confirmed_by_uid IS NULL AND confirmed_at IS NULL)
    OR (source ~ '^ai(_|$)' AND nullif(btrim(confirmed_by_uid), '') IS NOT NULL
        AND confirmed_at IS NOT NULL)
  )
);

CREATE FUNCTION public.actions_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = public AS $guard$
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF (NEW.person_id, NEW.opportunity_id, NEW.interaction_id, NEW.activity_id,
        NEW.source, NEW.created_by_uid, NEW.confirmed_by_uid, NEW.confirmed_at)
       IS DISTINCT FROM
       (OLD.person_id, OLD.opportunity_id, OLD.interaction_id, OLD.activity_id,
        OLD.source, OLD.created_by_uid, OLD.confirmed_by_uid, OLD.confirmed_at) THEN
      RAISE EXCEPTION 'action identity, links and provenance are immutable'
        USING ERRCODE = '23514';
    END IF;
    NEW.updated_at := now();
  END IF;
  IF NEW.interaction_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.interactions AS i
    WHERE i.id = NEW.interaction_id AND i.person_id = NEW.person_id
  ) THEN
    RAISE EXCEPTION 'action interaction belongs to another Person'
      USING ERRCODE = '23514';
  END IF;
  IF NEW.opportunity_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.opportunities AS o
    JOIN public.persons AS p ON p.id = NEW.person_id
    WHERE o.id = NEW.opportunity_id AND o.customer_id = p.legacy_customer_id
  ) THEN
    RAISE EXCEPTION 'action opportunity belongs to another Person'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$guard$;

CREATE TRIGGER actions_guard_before_write
  BEFORE INSERT OR UPDATE ON public.actions
  FOR EACH ROW EXECUTE FUNCTION public.actions_guard();

CREATE INDEX actions_person_status_due_idx
  ON public.actions(person_id, status, due_at, id);
CREATE INDEX actions_open_due_idx
  ON public.actions(due_at, id) WHERE status IN ('open', 'in_progress');
CREATE INDEX actions_opportunity_idx
  ON public.actions(opportunity_id) WHERE opportunity_id IS NOT NULL;
CREATE INDEX actions_interaction_idx
  ON public.actions(interaction_id) WHERE interaction_id IS NOT NULL;
CREATE INDEX actions_activity_idx
  ON public.actions(activity_id) WHERE activity_id IS NOT NULL;

ALTER TABLE public.actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.actions FORCE ROW LEVEL SECURITY;
CREATE POLICY actions_service_only ON public.actions FOR ALL TO service_role
  USING (true) WITH CHECK (true);
REVOKE ALL ON TABLE public.actions FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.actions TO service_role;
REVOKE ALL ON SEQUENCE public.actions_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.actions_id_seq TO service_role;
REVOKE ALL ON FUNCTION public.actions_guard() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.actions_guard() TO service_role;

COMMENT ON TABLE public.actions IS
  'Person-level action ledger; additive to legacy next_action fields and v_action_center';
COMMENT ON COLUMN public.actions.priority_score IS
  'Optional stored score from 0 to 100; no automatic ranking formula is applied';
COMMENT ON COLUMN public.actions.source IS
  'Manual actions or future explicitly confirmed AI actions; AI source requires confirmation audit';
COMMIT;
