-- Conversation Playbook storage only; no existing Skill or UI behavior changes.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

DO $guard$ BEGIN
  IF to_regclass('public.playbooks') IS NOT NULL
     OR to_regclass('public.playbooks_id_seq') IS NOT NULL THEN
    RAISE EXCEPTION 'public.playbooks objects already exist; inspect before migrating';
  END IF;
  IF to_regclass('public.knowledge_items') IS NULL THEN
    RAISE EXCEPTION 'public.knowledge_items must exist before playbooks';
  END IF;
END $guard$;

CREATE TABLE public.playbooks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scenario text NOT NULL CHECK (length(btrim(scenario)) BETWEEN 1 AND 256),
  objection text CHECK (objection IS NULL OR length(btrim(objection)) > 0),
  possible_underlying_reasons text[] NOT NULL DEFAULT '{}'::text[],
  clarifying_questions text[] NOT NULL DEFAULT '{}'::text[],
  response_logic text NOT NULL CHECK (length(btrim(response_logic)) > 0),
  evidence_refs bigint[] NOT NULL DEFAULT '{}'::bigint[],
  case_refs bigint[] NOT NULL DEFAULT '{}'::bigint[],
  story_refs bigint[] NOT NULL DEFAULT '{}'::bigint[],
  do_not_say text[] NOT NULL DEFAULT '{}'::text[],
  next_objective text NOT NULL CHECK (length(btrim(next_objective)) > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT playbooks_evidence_refs_check CHECK (
    coalesce(array_ndims(evidence_refs), 1) = 1
    AND array_position(evidence_refs, NULL) IS NULL
    AND 0 < ALL(evidence_refs)
  ),
  CONSTRAINT playbooks_case_refs_check CHECK (
    coalesce(array_ndims(case_refs), 1) = 1
    AND array_position(case_refs, NULL) IS NULL
    AND 0 < ALL(case_refs)
  ),
  CONSTRAINT playbooks_story_refs_check CHECK (
    coalesce(array_ndims(story_refs), 1) = 1
    AND array_position(story_refs, NULL) IS NULL
    AND 0 < ALL(story_refs)
  )
);

CREATE INDEX playbooks_scenario_idx ON public.playbooks(scenario);

ALTER TABLE public.playbooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.playbooks FORCE ROW LEVEL SECURITY;
CREATE POLICY playbooks_service_read ON public.playbooks
  FOR SELECT TO service_role USING (true);
CREATE POLICY playbooks_service_insert ON public.playbooks
  FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY playbooks_service_update ON public.playbooks
  FOR UPDATE TO service_role USING (true) WITH CHECK (true);
REVOKE ALL ON TABLE public.playbooks FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.playbooks TO service_role;
REVOKE ALL ON SEQUENCE public.playbooks_id_seq FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.playbooks_id_seq TO service_role;

COMMENT ON TABLE public.playbooks IS
  'Conversation Playbook content; recommendations require human review before affecting CRM facts';
COMMENT ON COLUMN public.playbooks.objection IS
  'Optional for proactive scenarios with no expressed objection';
COMMENT ON COLUMN public.playbooks.response_logic IS
  'Provider-neutral reasoning framework, not a fixed model prompt';
COMMENT ON COLUMN public.playbooks.evidence_refs IS
  'IDs intended for public.knowledge_items with item_type=evidence; resolve and verify at read time';
COMMENT ON COLUMN public.playbooks.case_refs IS
  'IDs intended for public.knowledge_items with item_type=case; resolve and verify at read time';
COMMENT ON COLUMN public.playbooks.story_refs IS
  'IDs intended for public.knowledge_items with item_type=story; resolve and verify at read time';
COMMIT;
